// Generated by GraphWalker (http://www.graphwalker.org)
package Graphs;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "Graphs/elevator_v5.json")
public interface ElevatorTest {

    @Edge()
    void existsAnotherRequest();

    @Vertex()
    void h_History();

    @Edge()
    void requestStopFromOtherFloor();

    @Vertex()
    void v_StopElevator();

    @Edge()
    void closeDoor();

    @Edge()
    void startGroup();

    @Edge()
    void noMoreRequest();

    @Edge()
    void wrongInput();

    @Vertex()
    void Idle();

    @Vertex()
    void PreparingToMove();

    @Edge()
    void stopRequestON();

    @Vertex()
    void v_Start();

    @Vertex()
    void FindNextDestination();

    @Edge()
    void requestElevatorFromFloorDown();

    @Edge()
    void requestElevatorFromFloorUp();

    @Edge()
    void stopRequestOFF();
}
